import Link from "next/link";import {ArrowDownRight, Sparkles} from "lucide-react";import {Suspense} from "react";import {getFeed} from "@/lib/posts";import {PostCard} from "@/components/post-card";import {SearchBox} from "@/components/search-box";import {Reveal} from "@/components/reveal";
export const dynamic="force-dynamic";
export default async function Home({searchParams}:{searchParams:Promise<{q?:string;tag?:string}>}){const {q,tag}=await searchParams;const posts=await getFeed(tag,q);return <main>
 <section className="container-folio pb-14 pt-16 md:pb-24 md:pt-28"><Reveal><div className="mb-8 flex items-center gap-2"><span className="size-2 animate-pulse rounded-full bg-accent"/><span className="eyebrow">Independent ideas, thoughtfully told</span></div><h1 className="max-w-5xl font-serif text-[clamp(3.5rem,9vw,8.5rem)] font-semibold leading-[.86] tracking-[-.06em]">Read less.<br/><span className="italic text-accent">Feel more.</span></h1></Reveal>
 <Reveal delay={.12} className="mt-10 flex flex-col justify-between gap-8 border-t border-line pt-7 md:flex-row md:items-end"><p className="max-w-md text-lg leading-7 text-muted">A quiet corner of the internet for curious minds. No paywalls, no noise—just ideas worth your time.</p><Link href="#stories" className="flex items-center gap-4 text-sm font-bold"><span className="grid size-12 place-items-center rounded-full border border-line"><ArrowDownRight size={19}/></span>Explore today’s stories</Link></Reveal></section>
 <div className="overflow-hidden border-y border-line bg-lime py-3 text-[#171715]"><div className="flex w-max animate-marquee gap-10 whitespace-nowrap text-xs font-bold uppercase tracking-[.2em]">{[0,1].map(n=><div key={n} className="flex gap-10">Thoughtful writing <Sparkles size={14}/> Free forever <Sparkles size={14}/> Human stories <Sparkles size={14}/> Ideas that stay with you <Sparkles size={14}/></div>)}</div></div>
 <section id="stories" className="container-folio py-16 md:py-24"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow mb-3">The daily edit</p><h2 className="font-serif text-4xl font-semibold tracking-tight md:text-5xl">Stories for now</h2></div><Suspense><SearchBox/></Suspense></div>
 <div className="flex gap-2 overflow-x-auto pb-5">{["All","Design","Culture","Growth","Technology","Mindfulness"].map(t=><Link key={t} href={t==="All"?"/":`/?tag=${t.toLowerCase()}`} className={`shrink-0 rounded-full border px-4 py-2 text-xs font-semibold ${tag===t.toLowerCase()||(!tag&&t==="All")?"border-ink bg-ink text-paper":"border-line hover:border-ink"}`}>{t}</Link>)}</div>
 {posts.length?<div>{posts.map((p,i)=><PostCard key={p.id} post={p} index={i}/>)}</div>:<div className="card mt-10 py-24 text-center"><p className="font-serif text-3xl">No stories found.</p><Link href="/" className="mt-3 inline-block text-sm text-accent">Clear your search</Link></div>}
 </section>
 <section className="bg-ink py-20 text-paper"><div className="container-folio grid gap-10 md:grid-cols-2 md:items-end"><div><p className="eyebrow !text-paper/50">Your words belong here</p><h2 className="mt-4 font-serif text-5xl font-semibold leading-none md:text-7xl">Have something<br/><i className="text-lime">worth sharing?</i></h2></div><div className="md:justify-self-end"><p className="mb-6 max-w-sm text-paper/60">Join independent thinkers publishing freely. You own your voice. We just give it a beautiful home.</p><Link href="/register" className="inline-flex h-12 items-center rounded-full bg-lime px-6 text-sm font-bold text-[#171715]">Start your Folio — it’s free</Link></div></div></section>
 </main>}
