import { query } from "./db";
export type PostCard = { id:string; slug:string; title:string; subtitle:string; cover_url:string|null; reading_minutes:number; published_at:string; author_name:string; username:string; tags:string[]; likes:number };
export const demoPosts:PostCard[]=[
 {id:"demo-1",slug:"the-art-of-paying-attention",title:"The art of paying attention in a distracted world",subtitle:"What we choose to notice becomes the texture of our lives.",cover_url:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=85",reading_minutes:6,published_at:"2026-09-27",author_name:"Maya Chen",username:"mayachen",tags:["Mindfulness","Culture"],likes:284},
 {id:"demo-2",slug:"small-systems-big-change",title:"Small systems, big change",subtitle:"Forget ambitious goals. Build a life that makes the right things inevitable.",cover_url:"https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1200&q=85",reading_minutes:4,published_at:"2026-09-25",author_name:"Noah Williams",username:"noahwrites",tags:["Growth","Design"],likes:192},
 {id:"demo-3",slug:"cities-after-midnight",title:"Cities after midnight",subtitle:"A field guide to the quiet hours and the people who keep them alive.",cover_url:"https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1200&q=85",reading_minutes:8,published_at:"2026-09-22",author_name:"Elena Rossi",username:"elenarossi",tags:["Travel","Essay"],likes:417}
];
export async function getFeed(tag?:string,search?:string):Promise<PostCard[]> {
 try { const rows = await query<PostCard>(`SELECT p.id,p.slug,p.title,p.subtitle,p.cover_url,p.reading_minutes,p.published_at,u.name author_name,u.username,COALESCE(array_agg(DISTINCT t.name) FILTER (WHERE t.name IS NOT NULL),'{}') tags,count(DISTINCT l.user_id)::int likes FROM posts p JOIN users u ON u.id=p.author_id LEFT JOIN post_tags pt ON pt.post_id=p.id LEFT JOIN tags t ON t.id=pt.tag_id LEFT JOIN likes l ON l.post_id=p.id WHERE p.status='published' AND ($1::text IS NULL OR t.slug=$1) AND ($2::text IS NULL OR p.title ILIKE '%'||$2||'%' OR p.subtitle ILIKE '%'||$2||'%') GROUP BY p.id,u.id ORDER BY p.published_at DESC LIMIT 24`,[tag||null,search||null]); return rows.length || tag || search ? rows : demoPosts; } catch { return demoPosts; }
}
